spring.application.name=matrix168
server.port=8081
spring.web.error.include-message=always

spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sophie333
spring.datasource.driver-class-name=org.postgresql.Driver

#//??????? Hibernate ?? ????? "????????" SQL ???????? ? ??
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#generating psql table
spring.jpa.generate-ddl=true

